databases:
  - name: sigmadb
    plan: free
    databaseName: sigma
    user: sigma

services:
  - type: web
    plan: free
    name: sigma
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sigma.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sigmadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4