# Generated by Django 5.0.2 on 2024-02-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyreport',
            old_name='title',
            new_name='victim',
        ),
    ]
