# Generated by Django 5.0.2 on 2024-02-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_emergencyreport_victim'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='finished_dosage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
