# Generated by Django 5.0.2 on 2024-02-20 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genotype',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='height',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='how_did_you_hear_about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='what_will_you_use_sigma_for',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
            },
        ),
    ]
