# Generated by Django 5.0.2 on 2024-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_allergies_remove_profile_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='what_will_you_use_sigma_for',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='allergies',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='blood_group',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='genotype',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='medical_history',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
