# Generated by Django 5.0.2 on 2024-02-14 00:28

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
                ('category', models.CharField(choices=[('Sex Education', 'Sex Education'), ('Food and Nutrition', 'Food and Nutrition'), ('Mental Health', 'Mental Health'), ('Physical Fitness', 'Physical Fitness'), ('First Aid', 'First Aid')], max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('featured_image', models.FileField(null=True, upload_to='course_images')),
                ('type', models.CharField(choices=[('Video Based Lecture', 'Video Based Lecture'), ('Text Based Lecture', 'Text Based Lecture'), ('Text And Video Based Lecture', 'Text And Video Based Lecture')], max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('sub_title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=300)),
                ('lecture_type', models.CharField(choices=[('Video Based Lecture', 'Video Based Lecture'), ('Text Based Lecture', 'Text Based Lecture'), ('Text And Video Based Lecture', 'Text And Video Based Lecture')], max_length=300)),
                ('youtube_url', models.URLField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
